### ISSUE TITLE
install fails for non-wheel pip dependencies

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#111]
Consider the following environment.yml

```yaml
dependencies:
  - python=3.10
  - pip
  - pip:
    - tranquilizer

channels:
  - defaults
```

The tranquilizer package [does not publish wheels](https://pypi.org/project/tranquilizer/#files) so solving the pip dependencies returns only tranquilizer.

```yaml
- category: main
  dependencies: {}
  hash:
    sha256: 6dbd5459d01012136fa75905592ba2725031034dbf916c54948cb524fcf16a18
  manager: pip
  name: tranquilizer
  optional: false
  platform: osx-arm64
  url: https://files.pythonhosted.org/packages/6b/3c/beb27cb6093ecbe3ac66f737b4f814140c873405f3209217fa65bb7f53cb/tranquilizer-0.3.0.tar.gz
  version: 0.3.0
```

This causes the install to fail with the following error:

```
Collecting tranquilizer@ https://files.pythonhosted.org/packages/6b/3c/beb27cb6093ecbe3ac66f737b4f814140c873405f3209217fa65bb7f53cb/tranquilizer-0.3.0.tar.gz#sha256=6dbd5459d01012136fa75905592ba2725031034dbf916c54948cb524fcf16a18 (from -r /var/folders/cg/wyhz9cvx06vdt65k8tr31trc0000gp/T/tmpaa4994q5 (line 1))
  Using cached tranquilizer-0.3.0.tar.gz (9.3 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

CondaProjectError: Failed to run:
  /Users/adefusco/Applications/miniconda3/bin/conda run -p /Users/adefusco/Development/conda-incubator/conda-project/examples/tranq/envs/default pip install --no-deps -r /var/folders/cg/wyhz9cvx06vdt65k8tr31trc0000gp/T/tmpaa4994q5
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/cg/wyhz9cvx06vdt65k8tr31trc0000gp/T/pip-install-ga1pzima/tranquilizer_5b81db6b7150403aac2c52b585d8ded6/setup.py", line 1, in <module>
          from version import find_version
      ModuleNotFoundError: No module named 'version'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

ERROR conda.cli.main_run:execute(47): `conda run pip install --no-deps -r /var/folders/cg/wyhz9cvx06vdt65k8tr31trc0000gp/T/tmpaa4994q5` failed. (See above for error)
```

**Comment by mattkram** [comment]
Have you tried this with another package? That sort of looks like an issue with versioneer not bundling the version file into the sdist.

**Comment by AlbertDeFusco** [comment]
Actually, the issue is a red herring. The old version of tranquilizer is a bad sdist to begin with. Switching to python 3.9 fixes the issue.

**Comment by mattkram** [comment]
👍 Let's close it then?
